version: '3.9'

services:
  api:
    build: ./server
    container_name: tasklist_api
    ports:
      - 5002:5002
    volumes:
      - .:/usr/src/app/server
    links:
      - database
    depends_on:
      - database
    env_file:
      - ./server/.env
    command: bash -c "sleep 20 && npm run migrate-dev && npm run dev"

  database:
    image: postgres
    container_name: database_taskList_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=taskList
      - POSTGRES_PASSWORD=taskList
      - POSTGRES_DB=taskList_api
    volumes:
      - pgdata:/data/postgres

  app:
    build: ./client
    container_name: app
    image: app
    volumes:
      - ./app:/app/app
    ports:
      - 3001:3001
  
volumes:
  pgdata:
    driver: local