version: '3.9'

services:
  database:
    image: postgres
    container_name: database_taskList_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=taskList
      - POSTGRES_PASSWORD=taskList
      - POSTGRES_DB=taskList_api
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local